# Laptop-specific Hyprland configuration
# Sourced by the shared hyprland config

# Laptop-specific brightness controls
binde=, XF86MonBrightnessUp, exec, brightnessctl -d 'amdgpu_bl1' s 2%+
binde=, XF86MonBrightnessDown, exec, brightnessctl -d 'amdgpu_bl1' s 2%-
