return {
  {
    "folke/which-key.nvim",
    event = "VeryLazy",
    dependencies = {
      "moll/vim-bbye",
    },
    opts = {
      win = {
        border = "rounded",
      },
    },
    keys = {
      -- { "<leader>a", "<cmd>Alpha<cr>", desc = "Alpha", nowait = true, remap = false },
      {
        "<leader>c",
        "<cmd>Bdelete!<CR>",
        desc = "Close Buffer",
        nowait = true,
        remap = false,
      },
      {
        "<leader>C",
        "<cmd>CopilotToggle<cr>",
        desc = "Copilot Toggle",
        nowait = true,
        remap = false,
      },
      {
        "<leader>d",
        group = "DAP",
        nowait = true,
        remap = false,
      },
      {
        "<leader>df",
        "<cmd>DapToggleBreakpoint<cr>",
        desc = "Toggle breakpoint",
        nowait = true,
        remap = false,
      },
      {
        "<leader>dg",
        "<cmd>DapContinue<cr>",
        desc = "Continue",
        nowait = true,
        remap = false,
      },
      {
        "<leader>dr",
        "<cmd>lua require('dapui').open({reset = true})<cr>",
        desc = "Reset UI",
        nowait = true,
        remap = false,
      },
      {
        "<leader>dt",
        "<cmd>lua require('dapui').toggle()<cr>",
        desc = "Toggle UI",
        nowait = true,
        remap = false,
      },
      {
        "<leader>g",
        group = "Git",
        nowait = true,
        remap = false,
      },
      {
        "<leader>gR",
        "<cmd>lua require 'gitsigns'.reset_buffer()<cr>",
        desc = "Reset Buffer",
        nowait = true,
        remap = false,
      },
      {
        "<leader>gd",
        "<cmd>Gitsigns diffthis HEAD<cr>",
        desc = "Diff",
        nowait = true,
        remap = false,
      },
      {
        "<leader>gj",
        "<cmd>lua require 'gitsigns'.next_hunk()<cr>",
        desc = "Next Hunk",
        nowait = true,
        remap = false,
      },
      {
        "<leader>gk",
        "<cmd>lua require 'gitsigns'.prev_hunk()<cr>",
        desc = "Prev Hunk",
        nowait = true,
        remap = false,
      },
      {
        "<leader>gl",
        "<cmd>lua require 'gitsigns'.blame_line()<cr>",
        desc = "Blame",
        nowait = true,
        remap = false,
      },
      {
        "<leader>gr",
        "<cmd>lua require 'gitsigns'.reset_hunk()<cr>",
        desc = "Reset Hunk",
        nowait = true,
        remap = false,
      },
      {
        "<leader>gs",
        "<cmd>lua require 'gitsigns'.stage_hunk()<cr>",
        desc = "Stage Hunk",
        nowait = true,
        remap = false,
      },
      {
        "<leader>gu",
        "<cmd>lua require 'gitsigns'.undo_stage_hunk()<cr>",
        desc = "Undo Stage Hunk",
        nowait = true,
        remap = false,
      },
      {
        "<leader>h",
        "<cmd>nohlsearch<CR>",
        desc = "No Highlight",
        nowait = true,
        remap = false,
      },
      {
        "<leader>l",
        group = "LSP",
        nowait = true,
        remap = false,
      },
      {
        "<leader>la",
        "<cmd>lua vim.lsp.buf.code_action()<cr>",
        desc = "Code Action",
        nowait = true,
        remap = false,
      },
      {
        "<leader>lf",
        "<cmd>lua vim.lsp.buf.format{async=true}<cr>",
        desc = "Format",
        nowait = true,
        remap = false,
      },
      {
        "<leader>li",
        "<cmd>LspInfo<cr>",
        desc = "Info",
        nowait = true,
        remap = false,
      },
      {
        "<leader>ll",
        "<cmd>lua vim.lsp.codelens.run()<cr>",
        desc = "CodeLens Action",
        nowait = true,
        remap = false,
      },
      {
        "<leader>lr",
        "<cmd>lua vim.lsp.buf.rename()<cr>",
        desc = "Rename",
        nowait = true,
        remap = false,
      },
      {
        "<leader>p",
        group = "Lazy",
        nowait = true,
        remap = false,
      },
      {
        "<leader>pS",
        "<cmd>Lazy health<cr>",
        desc = "Health",
        nowait = true,
        remap = false,
      },
      {
        "<leader>pc",
        "<cmd>Lazy build<cr>",
        desc = "Build",
        nowait = true,
        remap = false,
      },
      {
        "<leader>pi",
        "<cmd>Lazy install<cr>",
        desc = "Install",
        nowait = true,
        remap = false,
      },
      {
        "<leader>ps",
        "<cmd>Lazy sync<cr>",
        desc = "Sync",
        nowait = true,
        remap = false,
      },
      {
        "<leader>pu",
        "<cmd>Lazy update<cr>",
        desc = "Update",
        nowait = true,
        remap = false,
      },
      {
        "<leader>q",
        "<cmd>q!<CR>",
        desc = "Quit",
        nowait = true,
        remap = false,
      },
      {
        "<leader>r",
        group = "harpoon",
        nowait = true,
        remap = false,
      },
      {
        "<leader>ra",
        "<cmd>lua require('harpoon.mark').add_file()<cr>",
        desc = "Add mark",
        nowait = true,
        remap = false,
      },
      {
        "<leader>rj",
        "<cmd>lua require('harpoon.ui').nav_prev()<cr>",
        desc = "Navigate previous",
        nowait = true,
        remap = false,
      },
      {
        "<leader>rk",
        "<cmd>lua require('harpoon.ui').nav_next()<cr>",
        desc = "Navigate next",
        nowait = true,
        remap = false,
      },
      {
        "<leader>rr",
        "<cmd>lua require('harpoon.ui').toggle_quick_menu()<cr>",
        desc = "Toggle quick menu",
        nowait = true,
        remap = false,
      },
      {
        "<leader>s",
        group = "Search",
        nowait = true,
        remap = false,
      },
      {
        "<leader>t",
        group = "Terminal",
        nowait = true,
        remap = false,
      },
      {
        "<leader>tf",
        "<cmd>ToggleTerm direction=float<cr>",
        desc = "Float",
        nowait = true,
        remap = false,
      },
      {
        "<leader>th",
        "<cmd>ToggleTerm size=10 direction=horizontal<cr>",
        desc = "Horizontal",
        nowait = true,
        remap = false,
      },
      {
        "<leader>tn",
        "<cmd>lua _NODE_TOGGLE()<cr>",
        desc = "Node",
        nowait = true,
        remap = false,
      },
      {
        "<leader>tp",
        "<cmd>lua _PYTHON_TOGGLE()<cr>",
        desc = "Python",
        nowait = true,
        remap = false,
      },
      {
        "<leader>tt",
        "<cmd>lua _HTOP_TOGGLE()<cr>",
        desc = "Htop",
        nowait = true,
        remap = false,
      },
      {
        "<leader>tv",
        "<cmd>ToggleTerm size=80 direction=vertical<cr>",
        desc = "Vertical",
        nowait = true,
        remap = false,
      },
      {
        "<leader>ts",
        "<cmd>Screenkey<cr>",
        desc = "Screenkey",
        nowait = true,
        remap = false,
      },
      {
        "<leader>w",
        "<cmd>w!<CR>",
        desc = "Save",
        nowait = true,
        remap = false,
      },
      -- {
      --   "<leader>z",
      --   "<cmd>NeoZoomToggle<CR>",
      --   desc = "Toggle zoom",
      --   nowait = true,
      --   remap = false,
      -- }
    },
  },
}
