#!/bin/sh
HISTFILE="$HOME/.local/share"/zsh/history
# Check if the directory exists, if not create it
if [ ! -d "$(dirname "$HISTFILE")" ]; then
    mkdir -p "$(dirname "$HISTFILE")"
fi
# Check if the file exists, if not create it
if [ ! -f "$HISTFILE" ]; then
    touch "$HISTFILE"
fi
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export GOPATH=$HOME/.local/share/go
export PATH=$HOME/.miniconda/bin:$PATH

# fixes stdc++ libraries not found in clangd
# export CPLUS_INCLUDE_PATH=/usr/include/c++/11:/usr/include/x86_64-linux-gnu/c++/11
# eval "$(fnm env)"
# eval "$(zoxide init zsh)"
# eval "`pip completion --zsh`"
