console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '<>┌──(</><white>{{ .UserName }}</><red>@</><white>{{ .HostName }}</><>)</>'
    foreground = 'blue'
    background = 'transparent'
    type = 'session'
    style = 'plain'
    foreground_templates = ['{{ if .Root}}lightRed{{ end }}']

    [blocks.segments.properties]
      display_host = true

  [[blocks.segments]]
    foreground = 'cyan'
    background = 'transparent'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    template = '<magenta>{{ .HEAD }}</>{{if .BranchStatus }} <>{{ .BranchStatus }}</>{{ end }}{{ if .Working.Changed }} <red>{{ .Working.String }}</>{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} <green>{{ .Staging.String }}</>{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}'
    foreground = 'white'
    background = 'transparent'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      branch_icon = '<yellow></> '
      fetch_status = true
      fetch_upstream_icon = false

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    template = '{{ div .Ms 1000 }}s'
    foreground = 'yellow'
    background = 'transparent'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      threshold = 5000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '<blue>└─</>$'
    background = 'transparent'
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}green{{end}}']
